deploy:
  needs: build-analyze-scan
  runs-on: [aws-netflix]
  steps:
    # Step 1: Install Trivy
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    # Step 2: Pull the Docker Image
    - name: Pull the Docker Image
      run: docker pull pavan9505/netflix:latest

    # Step 3: Trivy Image Scan
    - name: Trivy Image Scan
      run: trivy image pavan9505/netflix:latest

    # Step 4: Run the Container
    - name: Run the Container Netflix
      run: docker run -d --name netflix -p 8081:80 pavan9505/netflix:latest
